using System;
using System.Collections.Generic;

namespace DotIt.AutoPicker.Models
{
    public partial class UserFile
    {
        public string DcdUserID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        //public bool AdvancedConfiguratorUser { get; set; }
        //public bool AdvBAQRights { get; set; }
        //public bool AllowMultipleSessions { get; set; }
        //public bool AllowReq { get; set; }
        //public bool AutoStartMonitor { get; set; }
        //public bool BAQXCompany { get; set; }
        //public int BitFlag { get; set; }
        //public bool BPMAdvancedUser { get; set; }
        //public bool CanAccEpiEverywhere { get; set; }
        //public bool CanAcessMobile { get; set; }
        //public bool CanChangePassword { get; set; }
        //public bool CanChangeSaveSettings { get; set; }
        //public bool CanCustomize { get; set; }
        //public bool CanDesignQSearch { get; set; }
        //public bool CanEditCompAnnotations { get; set; }
        //public string CanEditHelpLinks { get; set; }
        //public bool CanEditUserAnnotations { get; set; }
        //public bool CanMaintainFavPrograms { get; set; }
        //public bool CanMaintainFavQueries { get; set; }
        //public bool CanMaintainFavURLs { get; set; }
        //public bool CanMaintQuickSearch { get; set; }
        //public bool CanOverrideAllocations { get; set; }
        //public bool CanPersonalize { get; set; }
        //public bool CanSuspend { get; set; }
        //public bool CanTheme { get; set; }
        //public bool CanTranslate { get; set; }
        //public bool CanUseEntSearch { get; set; }
        public string City { get; set; }
       // public bool ClearPassword { get; set; }
        public string CompList { get; set; }
        public string Country { get; set; }
        public string CurComp { get; set; }
        public int CurFolderSeq { get; set; }
        public string CurMenuID { get; set; }
        public bool DashboardDeveloper { get; set; }
        public bool DispTips { get; set; }
        public string DomainName { get; set; }
        public bool DspPayrollMgr { get; set; }
        public bool DspPayrollMgrComp { get; set; }
        public string EMailAddress { get; set; }
        //public bool EnableDspPayrollMgr { get; set; }
        //public bool EnableDspPayrollMgrComp { get; set; }
        //public string EntConType { get; set; }
        //public string EntSearchURL { get; set; }
        //public bool ExpirePassword { get; set; }
        //public string FormatCulture { get; set; }
        //public string FormOpenMode { get; set; }
        //public bool GlbCompSM { get; set; }
        public string GroupList { get; set; }
        //public bool IsCurCompPayrollMgr { get; set; }
        //public string JCDept { get; set; }
        //public string LangNameID { get; set; }
        //public string LangNameIDDescription { get; set; }
        //public DateTime LastDate { get; set; }
        //public string LastGraphType { get; set; }
        //public int LastTime { get; set; }
        //public int ListViewMode { get; set; }
        //public int MaxGroupsFavorites { get; set; }
        //public int MaxGroupsSystemMenu { get; set; }
        //public string MobilePassword { get; set; }
        //public int MonitorPollingInterval { get; set; }
        public string Name { get; set; }
        public string OfficePhone { get; set; }
        //public string OSUserID { get; set; }
        //public string PayrollMgr { get; set; }
        public string Phone { get; set; }
        //public DateTime  PwdExpires { get; set; }
        //public int PwdExpiresDays { get; set; }
        //public int PwdGrace { get; set; }
        //public string PwdLastChanged { get; set; }
        //public bool RequireSso { get; set; }
        //public string RowMod { get; set; }
        //public bool SaveSettings { get; set; }
        //public bool SecurityAccessOnly { get; set; }
        //public bool SecurityMgr { get; set; }
        //public string ShopTrackerReuseLast { get; set; }
        //public int ShpTrackerIntMinute { get; set; }
        //public bool SolutionMgrCreate { get; set; }
        //public bool SolutionMgrInstall { get; set; }
        //public string StartMenuClient { get; set; }
        //public string StartMenuEWA { get; set; }
        //public string StartMenuMobile { get; set; }
        public string State { get; set; }
        public int SysRevID { get; set; }
        public string SysRowID { get; set; }
        //public bool TEAprRetrieveApproved { get; set; }
        //public bool TEAprRetrieveEntered { get; set; }
        //public bool TEAprRetrievePartiallyApproved { get; set; }
        //public bool TEAprRetrieveRejected { get; set; }
        //public bool TEAprRetrieveSubmitted { get; set; }
        //public bool TERetrieveApproved { get; set; }
        //public bool TERetrieveByDay { get; set; }
        //public bool TERetrieveByMonth { get; set; }
        //public bool TERetrieveByWeek { get; set; }
        //public bool TERetrieveEntered { get; set; }
        //public bool TERetrievePartiallyApproved { get; set; }
        //public bool TERetrieveRejected { get; set; }
        //public bool TERetrieveSubmitted { get; set; }
        //public int Timeout { get; set; }
        //public bool UseCompression { get; set; }
        //public bool UseDefaultEntSearch { get; set; }
        //public bool UseInternalWebBrowser { get; set; }
        //public bool UserAccessOnly { get; set; }
        //public bool UserDisabled { get; set; }
        //public bool ViewFavoriteBar { get; set; }
        //public bool ViewStatusBar { get; set; }
        //public bool ViewStatusPanelCompany { get; set; }
        //public bool ViewStatusPanelLanguage { get; set; }
        //public bool ViewStatusPanelPlant { get; set; }
        //public bool ViewStatusPanelServer { get; set; }
        //public bool ViewStatusPanelUserID { get; set; }
        //public bool ViewStatusPanelWorkstationID { get; set; }
        //public int ViewTreeOnly { get; set; }
        public bool WebUser { get; set; }
        public int WinHeight { get; set; }
        public int WinWidth { get; set; }
        public int WinX { get; set; }
        public int WinY { get; set; }
        public string ZIP { get; set; }
    }
}
