//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorDaily.Persistance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICKERORDER
    {
        public int ORDERNUM { get; set; }
        public string COMPANY { get; set; }
        public System.DateTime ORDERDATE { get; set; }
        public Nullable<int> TOTALITEMS { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public string DOCUSERID { get; set; }
        public string PICKSTATUS { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<System.DateTime> RECORDUPDATEDON { get; set; }
    }
}
