//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorDaily.Persistance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICKORDERDETAIL
    {
        public int ORDERNO { get; set; }
        public string COMPANY { get; set; }
        public string PARTNUM { get; set; }
        public string BINNUM { get; set; }
        public Nullable<int> DAMAGEQTY { get; set; }
        public Nullable<int> PICKSTATUS { get; set; }
    }
}
