//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorDaily.WSOrder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrder", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class SalesOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.DotitServiceResult dsrField;
        
        private int customerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerIdField;
        
        private int orderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderTypeField;
        
        private System.DateTime needByDateField;
        
        private bool useNeedByDateField;
        
        private System.DateTime requestDateField;
        
        private bool useRequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string poNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customerPONumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileField;
        
        private decimal ourRateField;
        
        private decimal publicRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trackingNumberField;
        
        private int packNumField;
        
        private bool isOrderHeldField;
        
        private bool isShipOrderCompleteField;
        
        private bool isCreditCardOrderField;
        
        private decimal miscFreightChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipToNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.Address addressShipToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.Address addressShipFromField;
        
        private bool shipToOneTimeField;
        
        private EpicorDaily.WSOrder.OrderCast orderCastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.Package tempPackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.Package[] listPackagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.SalesOrderLineItem[] listLineItemsField;
        
        private bool allLinesSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.SalesOrderLineItem[] listInvalidLineItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.ArrayOfString listCasedOrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EpicorDaily.WSOrder.DotitServiceResult dsr {
            get {
                return this.dsrField;
            }
            set {
                if ((object.ReferenceEquals(this.dsrField, value) != true)) {
                    this.dsrField = value;
                    this.RaisePropertyChanged("dsr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int customerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                if ((this.customerNumberField.Equals(value) != true)) {
                    this.customerNumberField = value;
                    this.RaisePropertyChanged("customerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.customerIdField, value) != true)) {
                    this.customerIdField = value;
                    this.RaisePropertyChanged("customerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                if ((this.orderNumberField.Equals(value) != true)) {
                    this.orderNumberField = value;
                    this.RaisePropertyChanged("orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string orderType {
            get {
                return this.orderTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.orderTypeField, value) != true)) {
                    this.orderTypeField = value;
                    this.RaisePropertyChanged("orderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime needByDate {
            get {
                return this.needByDateField;
            }
            set {
                if ((this.needByDateField.Equals(value) != true)) {
                    this.needByDateField = value;
                    this.RaisePropertyChanged("needByDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool useNeedByDate {
            get {
                return this.useNeedByDateField;
            }
            set {
                if ((this.useNeedByDateField.Equals(value) != true)) {
                    this.useNeedByDateField = value;
                    this.RaisePropertyChanged("useNeedByDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool useRequestDate {
            get {
                return this.useRequestDateField;
            }
            set {
                if ((this.useRequestDateField.Equals(value) != true)) {
                    this.useRequestDateField = value;
                    this.RaisePropertyChanged("useRequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sessionGUID {
            get {
                return this.sessionGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionGUIDField, value) != true)) {
                    this.sessionGUIDField = value;
                    this.RaisePropertyChanged("sessionGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string poNumber {
            get {
                return this.poNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.poNumberField, value) != true)) {
                    this.poNumberField = value;
                    this.RaisePropertyChanged("poNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string customerPONumber {
            get {
                return this.customerPONumberField;
            }
            set {
                if ((object.ReferenceEquals(this.customerPONumberField, value) != true)) {
                    this.customerPONumberField = value;
                    this.RaisePropertyChanged("customerPONumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string shipVia {
            get {
                return this.shipViaField;
            }
            set {
                if ((object.ReferenceEquals(this.shipViaField, value) != true)) {
                    this.shipViaField = value;
                    this.RaisePropertyChanged("shipVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string file {
            get {
                return this.fileField;
            }
            set {
                if ((object.ReferenceEquals(this.fileField, value) != true)) {
                    this.fileField = value;
                    this.RaisePropertyChanged("file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal ourRate {
            get {
                return this.ourRateField;
            }
            set {
                if ((this.ourRateField.Equals(value) != true)) {
                    this.ourRateField = value;
                    this.RaisePropertyChanged("ourRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public decimal publicRate {
            get {
                return this.publicRateField;
            }
            set {
                if ((this.publicRateField.Equals(value) != true)) {
                    this.publicRateField = value;
                    this.RaisePropertyChanged("publicRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.trackingNumberField, value) != true)) {
                    this.trackingNumberField = value;
                    this.RaisePropertyChanged("trackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int packNum {
            get {
                return this.packNumField;
            }
            set {
                if ((this.packNumField.Equals(value) != true)) {
                    this.packNumField = value;
                    this.RaisePropertyChanged("packNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool isOrderHeld {
            get {
                return this.isOrderHeldField;
            }
            set {
                if ((this.isOrderHeldField.Equals(value) != true)) {
                    this.isOrderHeldField = value;
                    this.RaisePropertyChanged("isOrderHeld");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public bool isShipOrderComplete {
            get {
                return this.isShipOrderCompleteField;
            }
            set {
                if ((this.isShipOrderCompleteField.Equals(value) != true)) {
                    this.isShipOrderCompleteField = value;
                    this.RaisePropertyChanged("isShipOrderComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool isCreditCardOrder {
            get {
                return this.isCreditCardOrderField;
            }
            set {
                if ((this.isCreditCardOrderField.Equals(value) != true)) {
                    this.isCreditCardOrderField = value;
                    this.RaisePropertyChanged("isCreditCardOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public decimal miscFreightCharge {
            get {
                return this.miscFreightChargeField;
            }
            set {
                if ((this.miscFreightChargeField.Equals(value) != true)) {
                    this.miscFreightChargeField = value;
                    this.RaisePropertyChanged("miscFreightCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string shipToNumber {
            get {
                return this.shipToNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.shipToNumberField, value) != true)) {
                    this.shipToNumberField = value;
                    this.RaisePropertyChanged("shipToNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public EpicorDaily.WSOrder.Address addressShipTo {
            get {
                return this.addressShipToField;
            }
            set {
                if ((object.ReferenceEquals(this.addressShipToField, value) != true)) {
                    this.addressShipToField = value;
                    this.RaisePropertyChanged("addressShipTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public EpicorDaily.WSOrder.Address addressShipFrom {
            get {
                return this.addressShipFromField;
            }
            set {
                if ((object.ReferenceEquals(this.addressShipFromField, value) != true)) {
                    this.addressShipFromField = value;
                    this.RaisePropertyChanged("addressShipFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public bool shipToOneTime {
            get {
                return this.shipToOneTimeField;
            }
            set {
                if ((this.shipToOneTimeField.Equals(value) != true)) {
                    this.shipToOneTimeField = value;
                    this.RaisePropertyChanged("shipToOneTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public EpicorDaily.WSOrder.OrderCast orderCast {
            get {
                return this.orderCastField;
            }
            set {
                if ((this.orderCastField.Equals(value) != true)) {
                    this.orderCastField = value;
                    this.RaisePropertyChanged("orderCast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public EpicorDaily.WSOrder.Package tempPack {
            get {
                return this.tempPackField;
            }
            set {
                if ((object.ReferenceEquals(this.tempPackField, value) != true)) {
                    this.tempPackField = value;
                    this.RaisePropertyChanged("tempPack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public EpicorDaily.WSOrder.Package[] listPackages {
            get {
                return this.listPackagesField;
            }
            set {
                if ((object.ReferenceEquals(this.listPackagesField, value) != true)) {
                    this.listPackagesField = value;
                    this.RaisePropertyChanged("listPackages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public EpicorDaily.WSOrder.SalesOrderLineItem[] listLineItems {
            get {
                return this.listLineItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.listLineItemsField, value) != true)) {
                    this.listLineItemsField = value;
                    this.RaisePropertyChanged("listLineItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public bool allLinesSuccess {
            get {
                return this.allLinesSuccessField;
            }
            set {
                if ((this.allLinesSuccessField.Equals(value) != true)) {
                    this.allLinesSuccessField = value;
                    this.RaisePropertyChanged("allLinesSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public EpicorDaily.WSOrder.SalesOrderLineItem[] listInvalidLineItems {
            get {
                return this.listInvalidLineItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.listInvalidLineItemsField, value) != true)) {
                    this.listInvalidLineItemsField = value;
                    this.RaisePropertyChanged("listInvalidLineItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public EpicorDaily.WSOrder.ArrayOfString listCasedOrders {
            get {
                return this.listCasedOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.listCasedOrdersField, value) != true)) {
                    this.listCasedOrdersField = value;
                    this.RaisePropertyChanged("listCasedOrders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DotitServiceResult", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class DotitServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool successField;
        
        private int returnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnMessageField;
        
        private int returnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.DLogMessage[] listMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                if ((this.returnCodeField.Equals(value) != true)) {
                    this.returnCodeField = value;
                    this.RaisePropertyChanged("returnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.returnMessageField, value) != true)) {
                    this.returnMessageField = value;
                    this.RaisePropertyChanged("returnMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int returnID {
            get {
                return this.returnIDField;
            }
            set {
                if ((this.returnIDField.Equals(value) != true)) {
                    this.returnIDField = value;
                    this.RaisePropertyChanged("returnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EpicorDaily.WSOrder.DLogMessage[] listMessages {
            get {
                return this.listMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.listMessagesField, value) != true)) {
                    this.listMessagesField = value;
                    this.RaisePropertyChanged("listMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipPlus4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        private bool isResidentialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactPhoneNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipperNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string upsAttnNameField;
        
        private bool isValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string line1 {
            get {
                return this.line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.line1Field, value) != true)) {
                    this.line1Field = value;
                    this.RaisePropertyChanged("line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string line2 {
            get {
                return this.line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.line2Field, value) != true)) {
                    this.line2Field = value;
                    this.RaisePropertyChanged("line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string line3 {
            get {
                return this.line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.line3Field, value) != true)) {
                    this.line3Field = value;
                    this.RaisePropertyChanged("line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string zipPlus4 {
            get {
                return this.zipPlus4Field;
            }
            set {
                if ((object.ReferenceEquals(this.zipPlus4Field, value) != true)) {
                    this.zipPlus4Field = value;
                    this.RaisePropertyChanged("zipPlus4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool isResidential {
            get {
                return this.isResidentialField;
            }
            set {
                if ((this.isResidentialField.Equals(value) != true)) {
                    this.isResidentialField = value;
                    this.RaisePropertyChanged("isResidential");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string contactName {
            get {
                return this.contactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.contactNameField, value) != true)) {
                    this.contactNameField = value;
                    this.RaisePropertyChanged("contactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string contactEmail {
            get {
                return this.contactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.contactEmailField, value) != true)) {
                    this.contactEmailField = value;
                    this.RaisePropertyChanged("contactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string contactPhoneNum {
            get {
                return this.contactPhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.contactPhoneNumField, value) != true)) {
                    this.contactPhoneNumField = value;
                    this.RaisePropertyChanged("contactPhoneNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string contactFax {
            get {
                return this.contactFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.contactFaxField, value) != true)) {
                    this.contactFaxField = value;
                    this.RaisePropertyChanged("contactFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string shipperNumber {
            get {
                return this.shipperNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.shipperNumberField, value) != true)) {
                    this.shipperNumberField = value;
                    this.RaisePropertyChanged("shipperNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string upsAttnName {
            get {
                return this.upsAttnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.upsAttnNameField, value) != true)) {
                    this.upsAttnNameField = value;
                    this.RaisePropertyChanged("upsAttnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                if ((this.isValidField.Equals(value) != true)) {
                    this.isValidField = value;
                    this.RaisePropertyChanged("isValid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Package", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class Package : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.Address shipToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.Address shipFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string upsServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string packageDescriptionField;
        
        private int orderNumberField;
        
        private int boxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purchaseOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        private int lineNumberField;
        
        private int releaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trackingNumberField;
        
        private decimal negotiatedRateField;
        
        private decimal publicRateField;
        
        private bool lastCallResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.DLogMessage[] resultMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.SalesOrderBox sizeField;
        
        private decimal qtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipToNumberField;
        
        private int packNumberField;
        
        private bool signatureRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string partNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string partDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string whseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string binField;
        
        private decimal widthField;
        
        private decimal heightField;
        
        private decimal lengthField;
        
        private decimal declaredValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string upsPackageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reference1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reference2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EpicorDaily.WSOrder.Address shipTo {
            get {
                return this.shipToField;
            }
            set {
                if ((object.ReferenceEquals(this.shipToField, value) != true)) {
                    this.shipToField = value;
                    this.RaisePropertyChanged("shipTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EpicorDaily.WSOrder.Address shipFrom {
            get {
                return this.shipFromField;
            }
            set {
                if ((object.ReferenceEquals(this.shipFromField, value) != true)) {
                    this.shipFromField = value;
                    this.RaisePropertyChanged("shipFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceTypeField, value) != true)) {
                    this.serviceTypeField = value;
                    this.RaisePropertyChanged("serviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string upsServiceCode {
            get {
                return this.upsServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.upsServiceCodeField, value) != true)) {
                    this.upsServiceCodeField = value;
                    this.RaisePropertyChanged("upsServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string packageDescription {
            get {
                return this.packageDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.packageDescriptionField, value) != true)) {
                    this.packageDescriptionField = value;
                    this.RaisePropertyChanged("packageDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                if ((this.orderNumberField.Equals(value) != true)) {
                    this.orderNumberField = value;
                    this.RaisePropertyChanged("orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int boxNumber {
            get {
                return this.boxNumberField;
            }
            set {
                if ((this.boxNumberField.Equals(value) != true)) {
                    this.boxNumberField = value;
                    this.RaisePropertyChanged("boxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string purchaseOrder {
            get {
                return this.purchaseOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.purchaseOrderField, value) != true)) {
                    this.purchaseOrderField = value;
                    this.RaisePropertyChanged("purchaseOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                if ((this.lineNumberField.Equals(value) != true)) {
                    this.lineNumberField = value;
                    this.RaisePropertyChanged("lineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int release {
            get {
                return this.releaseField;
            }
            set {
                if ((this.releaseField.Equals(value) != true)) {
                    this.releaseField = value;
                    this.RaisePropertyChanged("release");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.trackingNumberField, value) != true)) {
                    this.trackingNumberField = value;
                    this.RaisePropertyChanged("trackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal negotiatedRate {
            get {
                return this.negotiatedRateField;
            }
            set {
                if ((this.negotiatedRateField.Equals(value) != true)) {
                    this.negotiatedRateField = value;
                    this.RaisePropertyChanged("negotiatedRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal publicRate {
            get {
                return this.publicRateField;
            }
            set {
                if ((this.publicRateField.Equals(value) != true)) {
                    this.publicRateField = value;
                    this.RaisePropertyChanged("publicRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool lastCallResult {
            get {
                return this.lastCallResultField;
            }
            set {
                if ((this.lastCallResultField.Equals(value) != true)) {
                    this.lastCallResultField = value;
                    this.RaisePropertyChanged("lastCallResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public EpicorDaily.WSOrder.DLogMessage[] resultMessages {
            get {
                return this.resultMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.resultMessagesField, value) != true)) {
                    this.resultMessagesField = value;
                    this.RaisePropertyChanged("resultMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public EpicorDaily.WSOrder.SalesOrderBox size {
            get {
                return this.sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.sizeField, value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public decimal qty {
            get {
                return this.qtyField;
            }
            set {
                if ((this.qtyField.Equals(value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string shipToNumber {
            get {
                return this.shipToNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.shipToNumberField, value) != true)) {
                    this.shipToNumberField = value;
                    this.RaisePropertyChanged("shipToNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int packNumber {
            get {
                return this.packNumberField;
            }
            set {
                if ((this.packNumberField.Equals(value) != true)) {
                    this.packNumberField = value;
                    this.RaisePropertyChanged("packNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool signatureRequired {
            get {
                return this.signatureRequiredField;
            }
            set {
                if ((this.signatureRequiredField.Equals(value) != true)) {
                    this.signatureRequiredField = value;
                    this.RaisePropertyChanged("signatureRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string partNumber {
            get {
                return this.partNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.partNumberField, value) != true)) {
                    this.partNumberField = value;
                    this.RaisePropertyChanged("partNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string partDescription {
            get {
                return this.partDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.partDescriptionField, value) != true)) {
                    this.partDescriptionField = value;
                    this.RaisePropertyChanged("partDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string whseCode {
            get {
                return this.whseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.whseCodeField, value) != true)) {
                    this.whseCodeField = value;
                    this.RaisePropertyChanged("whseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string bin {
            get {
                return this.binField;
            }
            set {
                if ((object.ReferenceEquals(this.binField, value) != true)) {
                    this.binField = value;
                    this.RaisePropertyChanged("bin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public decimal width {
            get {
                return this.widthField;
            }
            set {
                if ((this.widthField.Equals(value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public decimal height {
            get {
                return this.heightField;
            }
            set {
                if ((this.heightField.Equals(value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public decimal length {
            get {
                return this.lengthField;
            }
            set {
                if ((this.lengthField.Equals(value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public decimal declaredValue {
            get {
                return this.declaredValueField;
            }
            set {
                if ((this.declaredValueField.Equals(value) != true)) {
                    this.declaredValueField = value;
                    this.RaisePropertyChanged("declaredValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string upsPackageType {
            get {
                return this.upsPackageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.upsPackageTypeField, value) != true)) {
                    this.upsPackageTypeField = value;
                    this.RaisePropertyChanged("upsPackageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string reference1 {
            get {
                return this.reference1Field;
            }
            set {
                if ((object.ReferenceEquals(this.reference1Field, value) != true)) {
                    this.reference1Field = value;
                    this.RaisePropertyChanged("reference1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string reference2 {
            get {
                return this.reference2Field;
            }
            set {
                if ((object.ReferenceEquals(this.reference2Field, value) != true)) {
                    this.reference2Field = value;
                    this.RaisePropertyChanged("reference2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderCast", Namespace="http://dotit.com.org/")]
    public enum OrderCast : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empty = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LinesOnly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LineWithReleases = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LinesSameQtyReleases = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LinesAndReleases = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderLineItem", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class SalesOrderLineItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lineItemNumberField;
        
        private bool lineSubmissionSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string submittedPartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnedPartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string submittedUOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnedUOMField;
        
        private decimal submittedQuantityField;
        
        private decimal returnedQuantityField;
        
        private decimal submittedUnitPriceField;
        
        private decimal returnedUnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string submittedPartDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnedPartDescriptionField;
        
        private decimal returnedPartWeightField;
        
        private int partsPerContainerField;
        
        private System.DateTime needByDateField;
        
        private int boxNumberField;
        
        private decimal boxWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.SalesOrderRelease[] listSalesOrderReleasesField;
        
        private bool allReleasesSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lineItemNumber {
            get {
                return this.lineItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.lineItemNumberField, value) != true)) {
                    this.lineItemNumberField = value;
                    this.RaisePropertyChanged("lineItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool lineSubmissionSuccess {
            get {
                return this.lineSubmissionSuccessField;
            }
            set {
                if ((this.lineSubmissionSuccessField.Equals(value) != true)) {
                    this.lineSubmissionSuccessField = value;
                    this.RaisePropertyChanged("lineSubmissionSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string submittedPartNumber {
            get {
                return this.submittedPartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.submittedPartNumberField, value) != true)) {
                    this.submittedPartNumberField = value;
                    this.RaisePropertyChanged("submittedPartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string returnedPartNumber {
            get {
                return this.returnedPartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.returnedPartNumberField, value) != true)) {
                    this.returnedPartNumberField = value;
                    this.RaisePropertyChanged("returnedPartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string submittedUOM {
            get {
                return this.submittedUOMField;
            }
            set {
                if ((object.ReferenceEquals(this.submittedUOMField, value) != true)) {
                    this.submittedUOMField = value;
                    this.RaisePropertyChanged("submittedUOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string returnedUOM {
            get {
                return this.returnedUOMField;
            }
            set {
                if ((object.ReferenceEquals(this.returnedUOMField, value) != true)) {
                    this.returnedUOMField = value;
                    this.RaisePropertyChanged("returnedUOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal submittedQuantity {
            get {
                return this.submittedQuantityField;
            }
            set {
                if ((this.submittedQuantityField.Equals(value) != true)) {
                    this.submittedQuantityField = value;
                    this.RaisePropertyChanged("submittedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal returnedQuantity {
            get {
                return this.returnedQuantityField;
            }
            set {
                if ((this.returnedQuantityField.Equals(value) != true)) {
                    this.returnedQuantityField = value;
                    this.RaisePropertyChanged("returnedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal submittedUnitPrice {
            get {
                return this.submittedUnitPriceField;
            }
            set {
                if ((this.submittedUnitPriceField.Equals(value) != true)) {
                    this.submittedUnitPriceField = value;
                    this.RaisePropertyChanged("submittedUnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal returnedUnitPrice {
            get {
                return this.returnedUnitPriceField;
            }
            set {
                if ((this.returnedUnitPriceField.Equals(value) != true)) {
                    this.returnedUnitPriceField = value;
                    this.RaisePropertyChanged("returnedUnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string submittedPartDescription {
            get {
                return this.submittedPartDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.submittedPartDescriptionField, value) != true)) {
                    this.submittedPartDescriptionField = value;
                    this.RaisePropertyChanged("submittedPartDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string returnedPartDescription {
            get {
                return this.returnedPartDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.returnedPartDescriptionField, value) != true)) {
                    this.returnedPartDescriptionField = value;
                    this.RaisePropertyChanged("returnedPartDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal returnedPartWeight {
            get {
                return this.returnedPartWeightField;
            }
            set {
                if ((this.returnedPartWeightField.Equals(value) != true)) {
                    this.returnedPartWeightField = value;
                    this.RaisePropertyChanged("returnedPartWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int partsPerContainer {
            get {
                return this.partsPerContainerField;
            }
            set {
                if ((this.partsPerContainerField.Equals(value) != true)) {
                    this.partsPerContainerField = value;
                    this.RaisePropertyChanged("partsPerContainer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.DateTime needByDate {
            get {
                return this.needByDateField;
            }
            set {
                if ((this.needByDateField.Equals(value) != true)) {
                    this.needByDateField = value;
                    this.RaisePropertyChanged("needByDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int boxNumber {
            get {
                return this.boxNumberField;
            }
            set {
                if ((this.boxNumberField.Equals(value) != true)) {
                    this.boxNumberField = value;
                    this.RaisePropertyChanged("boxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public decimal boxWeight {
            get {
                return this.boxWeightField;
            }
            set {
                if ((this.boxWeightField.Equals(value) != true)) {
                    this.boxWeightField = value;
                    this.RaisePropertyChanged("boxWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public EpicorDaily.WSOrder.SalesOrderRelease[] listSalesOrderReleases {
            get {
                return this.listSalesOrderReleasesField;
            }
            set {
                if ((object.ReferenceEquals(this.listSalesOrderReleasesField, value) != true)) {
                    this.listSalesOrderReleasesField = value;
                    this.RaisePropertyChanged("listSalesOrderReleases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool allReleasesSuccess {
            get {
                return this.allReleasesSuccessField;
            }
            set {
                if ((this.allReleasesSuccessField.Equals(value) != true)) {
                    this.allReleasesSuccessField = value;
                    this.RaisePropertyChanged("allReleasesSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.returnMessageField, value) != true)) {
                    this.returnMessageField = value;
                    this.RaisePropertyChanged("returnMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://dotit.com.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DLogMessage", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class DLogMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private EpicorDaily.WSOrder.LogLevel messageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        private bool notifyByEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public EpicorDaily.WSOrder.LogLevel messageType {
            get {
                return this.messageTypeField;
            }
            set {
                if ((this.messageTypeField.Equals(value) != true)) {
                    this.messageTypeField = value;
                    this.RaisePropertyChanged("messageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool notifyByEmail {
            get {
                return this.notifyByEmailField;
            }
            set {
                if ((this.notifyByEmailField.Equals(value) != true)) {
                    this.notifyByEmailField = value;
                    this.RaisePropertyChanged("notifyByEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogLevel", Namespace="http://dotit.com.org/")]
    public enum LogLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warn = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderBox", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class SalesOrderBox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int orderNumberField;
        
        private int boxNumberField;
        
        private decimal boxWeightField;
        
        private decimal boxCubicInchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trackingNumberField;
        
        private bool overWeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                if ((this.orderNumberField.Equals(value) != true)) {
                    this.orderNumberField = value;
                    this.RaisePropertyChanged("orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int boxNumber {
            get {
                return this.boxNumberField;
            }
            set {
                if ((this.boxNumberField.Equals(value) != true)) {
                    this.boxNumberField = value;
                    this.RaisePropertyChanged("boxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal boxWeight {
            get {
                return this.boxWeightField;
            }
            set {
                if ((this.boxWeightField.Equals(value) != true)) {
                    this.boxWeightField = value;
                    this.RaisePropertyChanged("boxWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal boxCubicInches {
            get {
                return this.boxCubicInchesField;
            }
            set {
                if ((this.boxCubicInchesField.Equals(value) != true)) {
                    this.boxCubicInchesField = value;
                    this.RaisePropertyChanged("boxCubicInches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.trackingNumberField, value) != true)) {
                    this.trackingNumberField = value;
                    this.RaisePropertyChanged("trackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool overWeight {
            get {
                return this.overWeightField;
            }
            set {
                if ((this.overWeightField.Equals(value) != true)) {
                    this.overWeightField = value;
                    this.RaisePropertyChanged("overWeight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderRelease", Namespace="http://dotit.com.org/")]
    [System.SerializableAttribute()]
    public partial class SalesOrderRelease : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string releaseField;
        
        private bool releaseSubmissionSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipToNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpicorDaily.WSOrder.Address shipToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trackingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string packNumField;
        
        private decimal ourRateField;
        
        private decimal publicRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string release {
            get {
                return this.releaseField;
            }
            set {
                if ((object.ReferenceEquals(this.releaseField, value) != true)) {
                    this.releaseField = value;
                    this.RaisePropertyChanged("release");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool releaseSubmissionSuccess {
            get {
                return this.releaseSubmissionSuccessField;
            }
            set {
                if ((this.releaseSubmissionSuccessField.Equals(value) != true)) {
                    this.releaseSubmissionSuccessField = value;
                    this.RaisePropertyChanged("releaseSubmissionSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderQty {
            get {
                return this.orderQtyField;
            }
            set {
                if ((object.ReferenceEquals(this.orderQtyField, value) != true)) {
                    this.orderQtyField = value;
                    this.RaisePropertyChanged("orderQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string shipToNumber {
            get {
                return this.shipToNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.shipToNumberField, value) != true)) {
                    this.shipToNumberField = value;
                    this.RaisePropertyChanged("shipToNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EpicorDaily.WSOrder.Address shipTo {
            get {
                return this.shipToField;
            }
            set {
                if ((object.ReferenceEquals(this.shipToField, value) != true)) {
                    this.shipToField = value;
                    this.RaisePropertyChanged("shipTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.trackingNumberField, value) != true)) {
                    this.trackingNumberField = value;
                    this.RaisePropertyChanged("trackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string packNum {
            get {
                return this.packNumField;
            }
            set {
                if ((object.ReferenceEquals(this.packNumField, value) != true)) {
                    this.packNumField = value;
                    this.RaisePropertyChanged("packNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal ourRate {
            get {
                return this.ourRateField;
            }
            set {
                if ((this.ourRateField.Equals(value) != true)) {
                    this.ourRateField = value;
                    this.RaisePropertyChanged("ourRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal publicRate {
            get {
                return this.publicRateField;
            }
            set {
                if ((this.publicRateField.Equals(value) != true)) {
                    this.publicRateField = value;
                    this.RaisePropertyChanged("publicRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dotit.com.org/", ConfigurationName="WSOrder.DotitOrdersSoap")]
    public interface DotitOrdersSoap {
        
        // CODEGEN: Generating message contract since element name sessionGuid from namespace http://dotit.com.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dotit.com.org/CreateSalesOrder", ReplyAction="*")]
        EpicorDaily.WSOrder.CreateSalesOrderResponse CreateSalesOrder(EpicorDaily.WSOrder.CreateSalesOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotit.com.org/CreateSalesOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<EpicorDaily.WSOrder.CreateSalesOrderResponse> CreateSalesOrderAsync(EpicorDaily.WSOrder.CreateSalesOrderRequest request);
        
        // CODEGEN: Generating message contract since element name sessionGuid from namespace http://dotit.com.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dotit.com.org/AddReleasesToOrder", ReplyAction="*")]
        EpicorDaily.WSOrder.AddReleasesToOrderResponse AddReleasesToOrder(EpicorDaily.WSOrder.AddReleasesToOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotit.com.org/AddReleasesToOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<EpicorDaily.WSOrder.AddReleasesToOrderResponse> AddReleasesToOrderAsync(EpicorDaily.WSOrder.AddReleasesToOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSalesOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSalesOrder", Namespace="http://dotit.com.org/", Order=0)]
        public EpicorDaily.WSOrder.CreateSalesOrderRequestBody Body;
        
        public CreateSalesOrderRequest() {
        }
        
        public CreateSalesOrderRequest(EpicorDaily.WSOrder.CreateSalesOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dotit.com.org/")]
    public partial class CreateSalesOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EpicorDaily.WSOrder.SalesOrder so;
        
        public CreateSalesOrderRequestBody() {
        }
        
        public CreateSalesOrderRequestBody(string sessionGuid, EpicorDaily.WSOrder.SalesOrder so) {
            this.sessionGuid = sessionGuid;
            this.so = so;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSalesOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSalesOrderResponse", Namespace="http://dotit.com.org/", Order=0)]
        public EpicorDaily.WSOrder.CreateSalesOrderResponseBody Body;
        
        public CreateSalesOrderResponse() {
        }
        
        public CreateSalesOrderResponse(EpicorDaily.WSOrder.CreateSalesOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dotit.com.org/")]
    public partial class CreateSalesOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EpicorDaily.WSOrder.SalesOrder CreateSalesOrderResult;
        
        public CreateSalesOrderResponseBody() {
        }
        
        public CreateSalesOrderResponseBody(EpicorDaily.WSOrder.SalesOrder CreateSalesOrderResult) {
            this.CreateSalesOrderResult = CreateSalesOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddReleasesToOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddReleasesToOrder", Namespace="http://dotit.com.org/", Order=0)]
        public EpicorDaily.WSOrder.AddReleasesToOrderRequestBody Body;
        
        public AddReleasesToOrderRequest() {
        }
        
        public AddReleasesToOrderRequest(EpicorDaily.WSOrder.AddReleasesToOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dotit.com.org/")]
    public partial class AddReleasesToOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EpicorDaily.WSOrder.SalesOrder so;
        
        public AddReleasesToOrderRequestBody() {
        }
        
        public AddReleasesToOrderRequestBody(string sessionGuid, EpicorDaily.WSOrder.SalesOrder so) {
            this.sessionGuid = sessionGuid;
            this.so = so;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddReleasesToOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddReleasesToOrderResponse", Namespace="http://dotit.com.org/", Order=0)]
        public EpicorDaily.WSOrder.AddReleasesToOrderResponseBody Body;
        
        public AddReleasesToOrderResponse() {
        }
        
        public AddReleasesToOrderResponse(EpicorDaily.WSOrder.AddReleasesToOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dotit.com.org/")]
    public partial class AddReleasesToOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EpicorDaily.WSOrder.SalesOrder AddReleasesToOrderResult;
        
        public AddReleasesToOrderResponseBody() {
        }
        
        public AddReleasesToOrderResponseBody(EpicorDaily.WSOrder.SalesOrder AddReleasesToOrderResult) {
            this.AddReleasesToOrderResult = AddReleasesToOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DotitOrdersSoapChannel : EpicorDaily.WSOrder.DotitOrdersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DotitOrdersSoapClient : System.ServiceModel.ClientBase<EpicorDaily.WSOrder.DotitOrdersSoap>, EpicorDaily.WSOrder.DotitOrdersSoap {
        
        public DotitOrdersSoapClient() {
        }
        
        public DotitOrdersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DotitOrdersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DotitOrdersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DotitOrdersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EpicorDaily.WSOrder.CreateSalesOrderResponse EpicorDaily.WSOrder.DotitOrdersSoap.CreateSalesOrder(EpicorDaily.WSOrder.CreateSalesOrderRequest request) {
            return base.Channel.CreateSalesOrder(request);
        }
        
        public EpicorDaily.WSOrder.SalesOrder CreateSalesOrder(string sessionGuid, EpicorDaily.WSOrder.SalesOrder so) {
            EpicorDaily.WSOrder.CreateSalesOrderRequest inValue = new EpicorDaily.WSOrder.CreateSalesOrderRequest();
            inValue.Body = new EpicorDaily.WSOrder.CreateSalesOrderRequestBody();
            inValue.Body.sessionGuid = sessionGuid;
            inValue.Body.so = so;
            EpicorDaily.WSOrder.CreateSalesOrderResponse retVal = ((EpicorDaily.WSOrder.DotitOrdersSoap)(this)).CreateSalesOrder(inValue);
            return retVal.Body.CreateSalesOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EpicorDaily.WSOrder.CreateSalesOrderResponse> EpicorDaily.WSOrder.DotitOrdersSoap.CreateSalesOrderAsync(EpicorDaily.WSOrder.CreateSalesOrderRequest request) {
            return base.Channel.CreateSalesOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<EpicorDaily.WSOrder.CreateSalesOrderResponse> CreateSalesOrderAsync(string sessionGuid, EpicorDaily.WSOrder.SalesOrder so) {
            EpicorDaily.WSOrder.CreateSalesOrderRequest inValue = new EpicorDaily.WSOrder.CreateSalesOrderRequest();
            inValue.Body = new EpicorDaily.WSOrder.CreateSalesOrderRequestBody();
            inValue.Body.sessionGuid = sessionGuid;
            inValue.Body.so = so;
            return ((EpicorDaily.WSOrder.DotitOrdersSoap)(this)).CreateSalesOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EpicorDaily.WSOrder.AddReleasesToOrderResponse EpicorDaily.WSOrder.DotitOrdersSoap.AddReleasesToOrder(EpicorDaily.WSOrder.AddReleasesToOrderRequest request) {
            return base.Channel.AddReleasesToOrder(request);
        }
        
        public EpicorDaily.WSOrder.SalesOrder AddReleasesToOrder(string sessionGuid, EpicorDaily.WSOrder.SalesOrder so) {
            EpicorDaily.WSOrder.AddReleasesToOrderRequest inValue = new EpicorDaily.WSOrder.AddReleasesToOrderRequest();
            inValue.Body = new EpicorDaily.WSOrder.AddReleasesToOrderRequestBody();
            inValue.Body.sessionGuid = sessionGuid;
            inValue.Body.so = so;
            EpicorDaily.WSOrder.AddReleasesToOrderResponse retVal = ((EpicorDaily.WSOrder.DotitOrdersSoap)(this)).AddReleasesToOrder(inValue);
            return retVal.Body.AddReleasesToOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EpicorDaily.WSOrder.AddReleasesToOrderResponse> EpicorDaily.WSOrder.DotitOrdersSoap.AddReleasesToOrderAsync(EpicorDaily.WSOrder.AddReleasesToOrderRequest request) {
            return base.Channel.AddReleasesToOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<EpicorDaily.WSOrder.AddReleasesToOrderResponse> AddReleasesToOrderAsync(string sessionGuid, EpicorDaily.WSOrder.SalesOrder so) {
            EpicorDaily.WSOrder.AddReleasesToOrderRequest inValue = new EpicorDaily.WSOrder.AddReleasesToOrderRequest();
            inValue.Body = new EpicorDaily.WSOrder.AddReleasesToOrderRequestBody();
            inValue.Body.sessionGuid = sessionGuid;
            inValue.Body.so = so;
            return ((EpicorDaily.WSOrder.DotitOrdersSoap)(this)).AddReleasesToOrderAsync(inValue);
        }
    }
}
